# Generated by Django 4.1.5 on 2023-01-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(default='Comedy', max_length=64),
        ),
    ]
