# Generated by Django 3.2.12 on 2023-02-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_borrow_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='copies',
        ),
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.IntegerField(default=1),
        ),
    ]
