# Generated by Django 3.2.12 on 2023-02-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_auto_20230202_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
